name: mini_project_x
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  animated_splash_screen: ^1.3.0
  bouncing_widget: ^2.0.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  get: ^4.6.5

flutter:
  uses-material-design: true

  assets:
    - materials/

  fonts:
    - family: Pacifico
      fonts:
        - asset: materials/fonts/Pacifico-Regular.ttf
    - family: JotiOne
      fonts:
        - asset: materials/fonts/JotiOne-Regular.ttf
